DROP TABLE IF EXISTS client_holdings;
DROP TABLE IF EXISTS client_trades;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS instruments;
DROP TABLE IF EXISTS advisors;
DROP TABLE IF EXISTS model_portfolios;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE advisors (
    advisor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advisor_name VARCHAR(255) NOT NULL,
    user_id INTEGER UNIQUE REFERENCES users(user_id)
);

CREATE TABLE model_portfolios (
    model_portfolio_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE clients (
    client_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(255) NOT NULL,
    advisor_id INTEGER REFERENCES advisors(advisor_id),
    model_portfolio_id INTEGER REFERENCES model_portfolios(model_portfolio_id),
    created_by_user_id INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cash_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE instruments (
    instrument_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_name VARCHAR(255) NOT NULL UNIQUE,
    ticker VARCHAR(255) NOT NULL UNIQUE,
    currency VARCHAR(50) NOT NULL,
    asset_class VARCHAR(255),
    security_type VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE client_trades (
    trade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES clients(client_id),
    instrument_id INTEGER NOT NULL REFERENCES instruments(instrument_id),
    submitted_by_user_id INTEGER REFERENCES users(user_id),
    approved_by_user_id INTEGER REFERENCES users(user_id),
    trade_type VARCHAR(10) NOT NULL,
    quantity DECIMAL(18,6) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    trade_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    executed_at TIMESTAMP,
    reason VARCHAR(500)
);

CREATE TABLE client_holdings (
    holding_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES clients(client_id),
    instrument_id INTEGER NOT NULL REFERENCES instruments(instrument_id),
    quantity DECIMAL(18,6) NOT NULL,
    as_of_date DATE NOT NULL,
    UNIQUE (client_id, instrument_id, as_of_date)
);

