DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS trade_suggestions;
DROP TABLE IF EXISTS client_subscriptions;
DROP TABLE IF EXISTS client_profiles;
DROP TABLE IF EXISTS client_holdings;
DROP TABLE IF EXISTS client_trades;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS model_portfolio_holdings;
DROP TABLE IF EXISTS advisors;
DROP TABLE IF EXISTS instruments;
DROP TABLE IF EXISTS model_portfolios;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    role_id INTEGER NOT NULL REFERENCES roles(role_id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE advisors (
    advisor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advisor_name VARCHAR(255) NOT NULL,
    user_id INTEGER UNIQUE REFERENCES users(user_id)
);

CREATE TABLE model_portfolios (
    model_portfolio_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE instruments (
    instrument_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_name VARCHAR(255) NOT NULL UNIQUE,
    ticker VARCHAR(255) NOT NULL UNIQUE,
    currency VARCHAR(50) NOT NULL,
    asset_class VARCHAR(255),
    security_type VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE clients (
    client_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES users(user_id),
    client_name VARCHAR(255) NOT NULL,
    advisor_id INTEGER REFERENCES advisors(advisor_id),
    model_portfolio_id INTEGER REFERENCES model_portfolios(model_portfolio_id),
    created_by_user_id INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cash_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE client_profiles (
    client_profile_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(user_id),
    client_id INTEGER UNIQUE REFERENCES clients(client_id),
    phone VARCHAR(255),
    date_of_birth DATE,
    address_line_1 VARCHAR(255),
    address_line_2 VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    postal_code VARCHAR(50),
    country VARCHAR(255),
    employment_status VARCHAR(255),
    net_worth DECIMAL(18,2),
    risk_tolerance VARCHAR(255),
    investment_objective VARCHAR(255),
    preferred_contact_method VARCHAR(255),
    paperless_statements BOOLEAN NOT NULL DEFAULT TRUE,
    marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
    onboarding_complete BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE client_subscriptions (
    subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES clients(client_id),
    model_portfolio_id INTEGER NOT NULL REFERENCES model_portfolios(model_portfolio_id),
    subscribed_date DATE NOT NULL,
    ended_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    approved_by_user_id INTEGER REFERENCES users(user_id)
);

CREATE TABLE trade_suggestions (
    suggestion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advisor_id INTEGER NOT NULL REFERENCES advisors(advisor_id),
    client_id INTEGER NOT NULL REFERENCES clients(client_id),
    instrument_id INTEGER NOT NULL REFERENCES instruments(instrument_id),
    trade_type VARCHAR(10) NOT NULL,
    quantity DECIMAL(18,6) NOT NULL,
    proposed_price DECIMAL(10,2),
    suggested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'SUGGESTED',
    notes VARCHAR(1000)
);

CREATE TABLE refresh_tokens (
    refresh_token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    audit_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id),
    entity_name VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255),
    action_type VARCHAR(255) NOT NULL,
    old_values VARCHAR(2000),
    new_values VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
