DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS client_subscriptions;
DROP TABLE IF EXISTS client_holdings;
DROP TABLE IF EXISTS client_trades;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS model_portfolio_holdings;
DROP TABLE IF EXISTS advisors;
DROP TABLE IF EXISTS instruments;
DROP TABLE IF EXISTS model_portfolios;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    role_id INTEGER NOT NULL REFERENCES roles(role_id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE advisors (
    advisor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advisor_name VARCHAR(255) NOT NULL,
    user_id INTEGER UNIQUE REFERENCES users(user_id)
);

CREATE TABLE model_portfolios (
    model_portfolio_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE clients (
    client_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(255) NOT NULL,
    advisor_id INTEGER REFERENCES advisors(advisor_id),
    model_portfolio_id INTEGER REFERENCES model_portfolios(model_portfolio_id),
    created_by_user_id INTEGER REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cash_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE client_subscriptions (
    subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES clients(client_id),
    model_portfolio_id INTEGER NOT NULL REFERENCES model_portfolios(model_portfolio_id),
    subscribed_date DATE NOT NULL,
    ended_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    approved_by_user_id INTEGER REFERENCES users(user_id)
);

CREATE TABLE audit_logs (
    audit_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id),
    entity_name VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255),
    action_type VARCHAR(255) NOT NULL,
    old_values VARCHAR(2000),
    new_values VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
